name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    - name: Build Docker image
  run: docker build -f path/to/Dockerfile .

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t myapp .

      - name: Run Tests
        run: docker run myapp npm test

      - name: Deploy Application
        run: docker compose up -d
